name: video_editor_example
description: The example project for the video_editor package.

publish_to: "none" 
version: 2.2.0+1

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_editor:
    path: ../

  fraction: ^4.1.4
  helpers: ^1.1.4
  image_picker: ^0.8.6+1
  path: ^1.8.2
  video_player: ^2.5.1

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1