name: video_editor
version: 1.2.2
description: Video Editor allows trim, crop, rotate and scale video with a super
  flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/shilangyu/ffmpeg-kit
      ref: development-flutter
      path: prebuilt/bundle-flutter-lts/default
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.2
  video_player: ^2.2.6
  video_thumbnail: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
