name: video_editor
version: 3.0.0
description: |
 A flutter package for editing video with fully customizable UI.
 Supports crop, trim, rotation and cover selection.
 Provides a flexible FFmpeg export configuration for consumers to use.
repository: https://github.com/LeGoffMael/video_editor

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  video_player: ^2.5.2
  cross_file: ^0.3.3+4
  # TODO(maRci002): remove local path when new package is published
  video_thumbnail:
    path: ../video_thumbnail/video_thumbnail

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp