name: video_editor
version: 1.3.0
description: A video editor that allows to trim, crop, rotate and scale video with a very flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_flutter_min_gpl: ^4.5.1
  path_provider: ^2.0.9
  video_player: ^2.3.0
  video_thumbnail: ^0.5.0
  path: ^1.8.0 # update to `1.8.1` causes #79

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4